spring:
  datasource:
    url: jdbc:mysql://192.168.64.2/usersdb?useSSL=false
    username: rachidba
    password: password
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  jpa:
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
        id:
          new_generator_mappings: false

server:
  port: 8092